<% production_host = ENV['WEBSOLR_URL'] || 'localhost' %>

production:
  solr:
    hostname: <%= production_host %>
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test: &TEST
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

cucumber:
  <<: *TEST
